#### Data Collection

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
data=pd.read_csv(r"D:\datas\project 3\database.csv")

In [2]:
data

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [3]:
data.Type.unique()

array(['Earthquake', 'Nuclear Explosion', 'Explosion', 'Rock Burst'],
      dtype=object)

we are considering only earthquake analysis

In [4]:
quake=data[data.Type=='Earthquake']

In [5]:
quake

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [6]:
quake.Type.unique()

array(['Earthquake'], dtype=object)

In [7]:
quake=quake.drop(['Type'],axis='columns')

In [8]:
quake.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Depth                             0
Depth Error                   18783
Depth Seismic Stations        16148
Magnitude                         0
Magnitude Type                    3
Magnitude Error               22917
Magnitude Seismic Stations    20772
Azimuthal Gap                 15946
Horizontal Distance           21637
Horizontal Error              22088
Root Mean Square               5985
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [9]:
quake=quake.fillna(value=0,inplace=False)

In [10]:
quake.describe()

,Latitude,Longitude,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square
count,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000,23232.000000
mean,1.386383,39.746049,71.313913,0.942449,84.096978,5.882763,0.000898,5.041236,13.738840,0.275097,0.330154,0.759840
std,29.929060,125.751903,122.968384,2.818881,155.305861,0.424032,0.008933,25.227371,26.710762,1.737635,1.777393,0.475717
min,-77.080000,-179.997000,-1.100000,0.000000,0.000000,5.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-18.719500,-76.366500,15.000000,0.000000,0.000000,5.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-3.680000,106.349000,33.000000,0.000000,0.000000,5.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.940000
75%,24.968500,145.290250,54.800000,0.000000,117.000000,6.000000,0.000000,0.000000,22.000000,0.000000,0.000000,1.100000
max,86.005000,179.998000,700.000000,91.295000,934.000000,9.100000,0.350000,821.000000,360.000000,37.874000,99.000000,3.220000

### Feature Engineering
We need to remove data those depth and magnitude and horizontal distance  errors are beyond than its upper and lower limit.Azimuth Gap greater than 180 will cause the location accuracy degrades significantly

In [11]:
quake=quake[quake['Azimuthal Gap']<180]
quake

,Date,Time,Latitude,Longitude,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,131.60,0.0,0.0,6.0,MW,0.000,0.0,0.00,0.000,0.0,0.0000,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,80.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,20.00,0.0,0.0,6.2,MW,0.000,0.0,0.00,0.000,0.0,0.0000,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,12.30,1.2,40.0,5.6,ML,0.320,18.0,42.47,0.120,0.0,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,8.80,2.0,33.0,5.5,ML,0.260,18.0,48.58,0.129,0.0,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,10.00,1.8,0.0,5.9,MWW,0.000,0.0,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,79.00,1.8,0.0,6.3,MWW,0.000,0.0,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,11.94,2.2,0.0,5.5,MB,0.029,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [12]:
quake.isnull().sum()

Date                          0
Time                          0
Latitude                      0
Longitude                     0
Depth                         0
Depth Error                   0
Depth Seismic Stations        0
Magnitude                     0
Magnitude Type                0
Magnitude Error               0
Magnitude Seismic Stations    0
Azimuthal Gap                 0
Horizontal Distance           0
Horizontal Error              0
Root Mean Square              0
ID                            0
Source                        0
Location Source               0
Magnitude Source              0
Status                        0
dtype: int64

In [13]:
quake.Status.unique()

array(['Automatic', 'Reviewed'], dtype=object)

In [14]:
quake_1=quake

In [15]:
quake_1['Longitude_r']=quake_1['Longitude'].round()

In [16]:
quake_1['Latitude_r']=quake_1['Latitude'].round()

In [17]:
quake_1=quake_1.drop(['ID','Source','Location Source','Magnitude Source','Latitude','Longitude','Status'],axis='columns')

In [18]:
quake_1

,Date,Time,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,Longitude_r,Latitude_r
0,01/02/1965,13:44:18,131.60,0.0,0.0,6.0,MW,0.000,0.0,0.00,0.000,0.0,0.0000,146.0,19.0
1,01/04/1965,11:29:49,80.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,127.0,2.0
2,01/05/1965,18:05:58,20.00,0.0,0.0,6.2,MW,0.000,0.0,0.00,0.000,0.0,0.0000,-174.0,-21.0
3,01/08/1965,18:49:43,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,-24.0,-59.0
4,01/09/1965,13:32:50,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,126.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,12.30,1.2,40.0,5.6,ML,0.320,18.0,42.47,0.120,0.0,0.1898,-119.0,38.0
23408,12/28/2016,09:13:47,8.80,2.0,33.0,5.5,ML,0.260,18.0,48.58,0.129,0.0,0.2187,-119.0,38.0
23409,12/28/2016,12:38:51,10.00,1.8,0.0,5.9,MWW,0.000,0.0,91.00,0.992,4.8,1.5200,140.0,37.0
23410,12/29/2016,22:30:19,79.00,1.8,0.0,6.3,MWW,0.000,0.0,26.00,3.553,6.0,1.4300,119.0,-9.0
23411,12/30/2016,20:08:28,11.94,2.2,0.0,5.5,MB,0.029,428.0,97.00,0.681,4.5,0.9100,141.0,37.0

In [19]:
quake_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23180 entries, 0 to 23411
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23180 non-null  object
 1   Time                        23180 non-null  object
 2   Depth                       23180 non-null  float64
 3   Depth Error                 23180 non-null  float64
 4   Depth Seismic Stations      23180 non-null  float64
 5   Magnitude                   23180 non-null  float64
 6   Magnitude Type              23180 non-null  object
 7   Magnitude Error             23180 non-null  float64
 8   Magnitude Seismic Stations  23180 non-null  float64
 9   Azimuthal Gap               23180 non-null  float64
 10  Horizontal Distance         23180 non-null  float64
 11  Horizontal Error            23180 non-null  float64
 12  Root Mean Square            23180 non-null  float64
 13  Longitude_r                 23180 non-null  float64
 14  Latitude_r                  23180 non-null  float64
dtypes: float64(12), object(3)
memory usage: 2.8+ MB

In [20]:
quake_1=quake_1[~(quake_1['Magnitude Type']==0)]
quake_1

,Date,Time,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,Longitude_r,Latitude_r
0,01/02/1965,13:44:18,131.60,0.0,0.0,6.0,MW,0.000,0.0,0.00,0.000,0.0,0.0000,146.0,19.0
1,01/04/1965,11:29:49,80.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,127.0,2.0
2,01/05/1965,18:05:58,20.00,0.0,0.0,6.2,MW,0.000,0.0,0.00,0.000,0.0,0.0000,-174.0,-21.0
3,01/08/1965,18:49:43,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,-24.0,-59.0
4,01/09/1965,13:32:50,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,126.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,12.30,1.2,40.0,5.6,ML,0.320,18.0,42.47,0.120,0.0,0.1898,-119.0,38.0
23408,12/28/2016,09:13:47,8.80,2.0,33.0,5.5,ML,0.260,18.0,48.58,0.129,0.0,0.2187,-119.0,38.0
23409,12/28/2016,12:38:51,10.00,1.8,0.0,5.9,MWW,0.000,0.0,91.00,0.992,4.8,1.5200,140.0,37.0
23410,12/29/2016,22:30:19,79.00,1.8,0.0,6.3,MWW,0.000,0.0,26.00,3.553,6.0,1.4300,119.0,-9.0
23411,12/30/2016,20:08:28,11.94,2.2,0.0,5.5,MB,0.029,428.0,97.00,0.681,4.5,0.9100,141.0,37.0

In [21]:
quake_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23177 entries, 0 to 23411
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23177 non-null  object
 1   Time                        23177 non-null  object
 2   Depth                       23177 non-null  float64
 3   Depth Error                 23177 non-null  float64
 4   Depth Seismic Stations      23177 non-null  float64
 5   Magnitude                   23177 non-null  float64
 6   Magnitude Type              23177 non-null  object
 7   Magnitude Error             23177 non-null  float64
 8   Magnitude Seismic Stations  23177 non-null  float64
 9   Azimuthal Gap               23177 non-null  float64
 10  Horizontal Distance         23177 non-null  float64
 11  Horizontal Error            23177 non-null  float64
 12  Root Mean Square            23177 non-null  float64
 13  Longitude_r                 23177 non-null  float64
 14  Latitude_r                  23177 non-null  float64
dtypes: float64(12), object(3)
memory usage: 2.8+ MB

In [22]:
quake_1=quake_1.drop('Time',axis='columns')

In [23]:
quake_1.Date= pd.to_datetime(quake_1.Date)
quake_1.Date

0        1965-01-02 00:00:00
1        1965-01-04 00:00:00
2        1965-01-05 00:00:00
3        1965-01-08 00:00:00
4        1965-01-09 00:00:00
                ...
23407    2016-12-28 00:00:00
23408    2016-12-28 00:00:00
23409    2016-12-28 00:00:00
23410    2016-12-29 00:00:00
23411    2016-12-30 00:00:00
Name: Date, Length: 23177, dtype: object

In [24]:
quake_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23177 entries, 0 to 23411
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23177 non-null  object
 1   Depth                       23177 non-null  float64
 2   Depth Error                 23177 non-null  float64
 3   Depth Seismic Stations      23177 non-null  float64
 4   Magnitude                   23177 non-null  float64
 5   Magnitude Type              23177 non-null  object
 6   Magnitude Error             23177 non-null  float64
 7   Magnitude Seismic Stations  23177 non-null  float64
 8   Azimuthal Gap               23177 non-null  float64
 9   Horizontal Distance         23177 non-null  float64
 10  Horizontal Error            23177 non-null  float64
 11  Root Mean Square            23177 non-null  float64
 12  Longitude_r                 23177 non-null  float64
 13  Latitude_r                  23177 non-null  float64
dtypes: float64(12), object(2)
memory usage: 2.7+ MB

In [25]:
quake_1

,Date,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,Longitude_r,Latitude_r
0,1965-01-02 00:00:00,131.60,0.0,0.0,6.0,MW,0.000,0.0,0.00,0.000,0.0,0.0000,146.0,19.0
1,1965-01-04 00:00:00,80.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,127.0,2.0
2,1965-01-05 00:00:00,20.00,0.0,0.0,6.2,MW,0.000,0.0,0.00,0.000,0.0,0.0000,-174.0,-21.0
3,1965-01-08 00:00:00,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,-24.0,-59.0
4,1965-01-09 00:00:00,15.00,0.0,0.0,5.8,MW,0.000,0.0,0.00,0.000,0.0,0.0000,126.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,2016-12-28 00:00:00,12.30,1.2,40.0,5.6,ML,0.320,18.0,42.47,0.120,0.0,0.1898,-119.0,38.0
23408,2016-12-28 00:00:00,8.80,2.0,33.0,5.5,ML,0.260,18.0,48.58,0.129,0.0,0.2187,-119.0,38.0
23409,2016-12-28 00:00:00,10.00,1.8,0.0,5.9,MWW,0.000,0.0,91.00,0.992,4.8,1.5200,140.0,37.0
23410,2016-12-29 00:00:00,79.00,1.8,0.0,6.3,MWW,0.000,0.0,26.00,3.553,6.0,1.4300,119.0,-9.0
23411,2016-12-30 00:00:00,11.94,2.2,0.0,5.5,MB,0.029,428.0,97.00,0.681,4.5,0.9100,141.0,37.0

Indian main land extends between latitudes 8°4'N and 37°6'N and longitudes 68°7'E and 97°25'E.so considering earthquake near India

In [27]:
quake_india=quake_1[(quake_1.Longitude_r>68)&(quake_1.Longitude_r<98)&(quake_1.Latitude_r>8)&(quake_1.Latitude_r<38)]
quake_india

,Date,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,Longitude_r,Latitude_r
6,1965-01-12 00:00:00,20.0,0.0,0.0,5.9,MW,0.0,0.0,0.0,0.000,0.0,0.00,88.0,27.0
58,1965-02-18 00:00:00,55.0,0.0,0.0,5.6,MW,0.0,0.0,0.0,0.000,0.0,0.00,94.0,25.0
87,1965-03-14 00:00:00,207.8,0.0,0.0,7.4,MW,0.0,0.0,0.0,0.000,0.0,0.00,71.0,36.0
179,1965-06-17 00:00:00,10.0,0.0,0.0,5.9,MW,0.0,0.0,0.0,0.000,0.0,0.00,88.0,32.0
339,1966-01-05 00:00:00,25.0,0.0,0.0,5.8,MW,0.0,0.0,0.0,0.000,0.0,0.00,95.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23047,2016-04-10 00:00:00,212.0,1.8,0.0,6.6,MWW,0.0,0.0,17.0,0.789,6.5,1.03,71.0,36.0
23052,2016-04-13 00:00:00,136.0,1.8,0.0,6.9,MWW,0.0,0.0,14.0,3.001,7.1,1.03,95.0,23.0
23226,2016-08-24 00:00:00,82.0,1.9,0.0,6.8,MWW,0.0,0.0,17.0,1.802,5.9,1.05,95.0,21.0
23293,2016-10-17 00:00:00,35.0,1.7,0.0,5.9,MWW,0.0,0.0,11.0,4.519,4.6,0.82,95.0,33.0
23396,2016-12-20 00:00:00,10.0,1.7,0.0,5.6,MWW,0.0,0.0,15.0,7.182,7.6,0.83,85.0,37.0